## FORCE METRICS
FORCE_FEATURES = [
    "ATIForceSensor_average_force_magnitude",
    "PSM1_forcen_magnitude",
    "PSM2_forcen_magnitude"
]

KINEMATICS = [
    "completion_time",
    "PSM1_average_speed_magnitude",
    "PSM2_average_speed_magnitude",
    "PSM1_total_path_length",
    "PSM2_total_path_length",
    "PSM1_average_angular_speed_magnitude",
    "PSM2_average_angular_speed_magnitude",
    "PSM1_PSM2_speed_correlation",
    "PSM1_PSM2_speed_cross"
]

KINETICS = [
    "ATIForceSensor_average_force_magnitude",
    "PSM1_forcen_magnitude",
    "PSM2_forcen_magnitude",
    "PSM1_average_acceleration_magnitude",
    "PSM2_average_acceleration_magnitude",
    "PSM1_PSM2_acceleration_cross",
    "PSM1_PSM2_jerk_dispertion",
    "PSM1_PSM2_forcen_cross",
    "PSM1_PSM2_forcen_correlation",
    "PSM1_PSM2_forcen_dispertion",
    "PSM1_average_jerk_magnitude",
    "PSM2_average_jerk_magnitude",
    "PSM1_average_jerk_magnitude_nT",
    "PSM2_average_jerk_magnitude_nT",
    "PSM1_average_jerk_magnitude_nPL",
    "PSM2_average_jerk_magnitude_nPL",
    "ATIForceSensor_average_force_magnitude",
    "ATIForceSensor_average_force_magnitude_nT",
    "ATIForceSensor_average_force_magnitude_nPL",
    "ATIForceSensor_max_force_magnitude",
    "ATIForceSensor_min_force_magnitude",
    "ATIForceSensor_max_force_x",
    "ATIForceSensor_max_force_y",
    "ATIForceSensor_max_force_z",
]

ALL_FEATURES = [
    "completion_time",
    "PSM1_average_speed_magnitude",
    "PSM2_average_speed_magnitude",
    "PSM1_average_acceleration_magnitude",
    "PSM2_average_acceleration_magnitude",
    "PSM1_average_jerk_magnitude",
    "PSM2_average_jerk_magnitude",
    "ATIForceSensor_average_force_magnitude",
    "PSM1_total_path_length",
    "PSM2_total_path_length",
    "PSM1_average_angular_speed_magnitude",
    "PSM2_average_angular_speed_magnitude",
    "PSM1_PSM2_speed_correlation",
    "PSM1_PSM2_speed_cross",
    "PSM1_PSM2_acceleration_cross",
    "PSM1_PSM2_jerk_cross",
    "PSM1_PSM2_acceleration_dispertion",
    "PSM1_PSM2_jerk_dispertion",
    "PSM1_forcen_magnitude",
    "PSM2_forcen_magnitude",
    # "PSM1_PMS2_forcen_cross",
]

ALL_FEATURES_NO_FORCEN = [
    "completion_time",
    "PSM1_average_speed_magnitude",
    "PSM2_average_speed_magnitude",
    "PSM1_average_acceleration_magnitude",
    "PSM2_average_acceleration_magnitude",
    "PSM1_average_jerk_magnitude",
    "PSM2_average_jerk_magnitude",
    "ATIForceSensor_average_force_magnitude",
    "PSM1_total_path_length",
    "PSM2_total_path_length",
    "PSM1_average_angular_speed_magnitude",
    "PSM2_average_angular_speed_magnitude",
    "PSM1_PSM2_speed_correlation",
    "PSM1_PSM2_speed_cross",
    "PSM1_PSM2_acceleration_cross",
    "PSM1_PSM2_jerk_cross",
    "PSM1_PSM2_acceleration_dispertion",
    "PSM1_PSM2_jerk_dispertion",
]